# Generated by Django 3.2.5 on 2021-08-03 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_user_normal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emp',
        ),
        migrations.AlterModelTable(
            name='user_normal',
            table=None,
        ),
    ]
