# Generated by Django 3.2.5 on 2021-08-03 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210803_1917'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_normal',
            table='user_normal',
        ),
    ]
